# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities.builtin.platform import message as platform_message
from langbot_plugin.api.entities import events, context

import requests
import random
import os
import base64
import hashlib
import time

class DefaultEventListener(EventListener):

    async def initialize(self):
        await super().initialize()
        
        @self.handler(events.NormalMessageResponded)
        async def handler(event_context):
            response_text = event_context.event.response_text
            print(f"📝 收到回复文本: {response_text}")

            # 设置TTS触发概率（100% = 每次都会语音回复）
            config = self.plugin.get_config()

            random_tts_probability = 100

            API_KEY = ""

            random_tts_probabilityt = config.get("random_tts_probability", 100)

            API_KEY = config.get("qhaitts_token", "")

            text = response_text

            voice = '魈'

            voice = config.get("qhaitts_voicer", "魈")

            close_reply = True

            close_reply =  config.get("close_reply", True)

            if random.randint(1, 100) <= random_tts_probability:

                
                print(f"🎤 开始生成语音，使用声线: {voice}")
                result = self.download_audio_from_api(API_KEY, voice, text)
                
                if result and not result.startswith("❌"):
                    if close_reply == True:
                        event_context.prevent_default()
                    try:
                        # 发送语音消息
                        await event_context.reply(
                            platform_message.MessageChain([
                                platform_message.Voice(base64=result)
                            ])
                        )
                        print("✅ 语音消息发送成功")
                        
                        # 清理缓存的语音文件（如果使用了文件缓存）
                        self.cleanup_audio_cache()
                        
                    except Exception as e:
                        print(f"❌ 语音发送失败: {e}")
                else: 
                    print(f"❌ 语音生成失败: {result}")

    def download_audio_from_api(self, api_key: str, voice: str, text: str):
        """
        直接从API下载音频并返回base64编码
        避免在本地创建文件，减少缓存问题
        """
        headers = {
            'Authorization': f"Bearer {api_key}", 
            'Content-Type': 'application/json'
        }
        data = {
            "model": "qhai-tts",
            "input": text,
            "voice": voice,
            "response_format": "wav"  # 明确指定格式
        }
        url = "https://api.qhaigc.net/v1/audio/speech"
        
        try:
            print(f"🔗 请求TTS API，文本长度: {len(text)} 字符")
            response = requests.post(url, headers=headers, json=data, timeout=30)
            
            if response.status_code == 200:
                # 将音频内容转换为base64编码
                audio_base64 = base64.b64encode(response.content).decode('utf-8')
                print(f"✅ 音频生成成功，大小: {len(audio_base64)} 字节(base64)")
                return audio_base64
            else:
                error_msg = f"❌ API请求失败: {response.status_code} - {response.text}"
                print(error_msg)
                return error_msg
                
        except requests.exceptions.Timeout:
            error_msg = "❌ 请求超时"
            print(error_msg)
            return error_msg
        except requests.exceptions.ConnectionError:
            error_msg = "❌ 网络连接错误"
            print(error_msg)
            return error_msg
        except Exception as e:
            error_msg = f"❌ 未知错误: {str(e)}"
            print(error_msg)
            return error_msg

    def cleanup_audio_cache(self):
        """
        清理可能存在的语音缓存
        由于我们使用base64直接发送，不保存文件，这里主要清理其他可能的缓存
        """
        try:
            # 检查临时目录中可能存在的语音缓存文件
            temp_dir = "/tmp" if os.name != 'nt' else os.environ.get('TEMP', '')
            
            if temp_dir and os.path.exists(temp_dir):
                # 查找可能的缓存文件（按你的实际情况调整）
                for filename in os.listdir(temp_dir):
                    if filename.startswith("speech_") or filename.endswith(".wav"):
                        try:
                            filepath = os.path.join(temp_dir, filename)
                            # 只删除旧文件（超过1小时的）
                            if time.time() - os.path.getmtime(filepath) > 3600:
                                os.remove(filepath)
                                print(f"🗑️ 清理缓存文件: {filename}")
                        except:
                            pass
        except Exception as e:
            print(f"⚠️ 缓存清理时出错: {e}")

# 如果需要文件缓存版本，可以使用这个函数
def download_and_cache_audio(api_key: str, voice: str, text: str, cache_dir: str = "/tmp/tts_cache"):
    """
    带缓存功能的版本，减少API调用
    """
    # 创建缓存目录
    os.makedirs(cache_dir, exist_ok=True)
    
    # 生成文本的hash作为文件名
    text_hash = hashlib.md5(text.encode()).hexdigest()
    cache_file = os.path.join(cache_dir, f"{voice}_{text_hash}.wav")
    
    # 检查缓存是否存在且有效
    if os.path.exists(cache_file):
        # 检查缓存是否过期（例如24小时）
        if time.time() - os.path.getmtime(cache_file) < 86400:
            print(f"📁 使用缓存文件: {cache_file}")
            with open(cache_file, 'rb') as f:
                return base64.b64encode(f.read()).decode('utf-8')
    
    # 没有缓存或已过期，调用API
    headers = {'Authorization': f"Bearer {api_key}", 'Content-Type': 'application/json'}
    data = {"model": "qhai-tts", "input": text, "voice": voice}
    url = "https://api.qhaigc.net/v1/audio/speech"
    
    try:
        response = requests.post(url, headers=headers, json=data, timeout=30)
        
        if response.status_code == 200:
            # 保存到缓存
            with open(cache_file, 'wb') as f:
                f.write(response.content)
            
            # 清理旧缓存（保持最多50个文件）
            cache_files = [os.path.join(cache_dir, f) for f in os.listdir(cache_dir)]
            cache_files.sort(key=lambda x: os.path.getmtime(x))
            while len(cache_files) > 50:
                try:
                    os.remove(cache_files[0])
                    cache_files.pop(0)
                except:
                    pass
            
            return base64.b64encode(response.content).decode('utf-8')
        else:
            return f"❌ 下载失败: {response.status_code}"
            
    except Exception as e:
        return f"❌ 错误: {e}"